use std::fs;


fn main() {
	let letters = "abcdefghijklmnopqrstxyz@";
	let colours = "r g b c m y lr lg lb lc lm ly a";
	let mut sprites: Vec<String> = Vec::new();
	
	for colour in colours.split(" ") {
		for letter in letters.chars() {
			sprites.push(format!("Sprite(\"player_{}-{}\")", colour, letter));
		}
	}
	let code = format!("
// Autogenerated. See build.rs
use crate::sprite::Sprite;

pub const PLAYER_SPRITES: &'static [Sprite] = &[
	{}
];
", sprites.join(",\n\t"));
	fs::write("src/sprite/player_sprites.rs", &code);
	println!("code: {}", code);
}
